// FIRST EXMAPLE STACK
export const EX_FIRST_STACK = "EX_FIRST_STACK";
// SECOND EXAMPLE STACK
export const EX_SECOND_STACK = "EX_SECOND_STACK";
// THIRD EXAMPLE STACK
export const EX_THIRD_STACK = "EX_THIRD_STACK";
export const SEARCH_CAT = "SEARCH_CAT";
export const SEARCH_TERM = "SEARCH_TERM";